version: '3'

services:
    mongo:
        image: mongo
        environment:
            - MONGO_INITDB_ROOT_USERNAME=mongoadmin
            - MONGO_INITDB_ROOT_PASSWORD=secret
            - MONGO_INITDB_DATABASE=nodejs
    mongo-express:
        image: mongo-express
        environment:
            - ME_CONFIG_MONGODB_SERVER=mongo
            - ME_CONFIG_MONGODB_PORT=27017
            - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
            - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
            - ME_CONFIG_MONGODB_AUTH_USERNAME=mongoadmin
            - ME_CONFIG_MONGODB_AUTH_PASSWORD=secret
        depends_on:
            - mongo
        ports:
          - "8081:8081"
    nodejs-tutorial:
        image: node-tutorial
        depends_on:
            - mongo
        ports:
          - "8888:8888"
        volumes:
          - C:\personal\workspace\node-tutorial\:/usr/src/app
